
addr: 0.0.0.0:5555 # 服务监听地址
timeout: 30s # 服务端超时
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5 # JWT 签发密钥
otel:
  endpoint: 127.0.0.1:4317
  service-name: art-apiserver
  output-mode: otel
  level: debug
  add-source: true
  use-prometheus-endpoint: true
  slog: # 改配置项只有 output-mod 为 slog 时生效
    format: text
    time-format: "2006-01-02 15:04:05"
    output: stdout
mysql:  
  addr: 127.0.0.1:3306
  username: art
  password: "123456"
  database: art
  max-connection-life-time: 10s
  max-idle-connections: 100
  max-open-connections: 100

