
addr: 0.0.0.0:5555 # 服务监听地址
timeout: 30s # 服务端超时
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5 # JWT 签发密钥
log: # 使用默认值即可，不需要在 manifests/env.local 中配置
    level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
    enable-color: true # 是否开启颜色输出，true: 是，false: 否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再 panic 及以上级别禁止打印堆栈信息
    output-paths: ["stdout"] # 多个输出，逗号分开。stdout：标准输出，stderr：标准错误输出，文件路径：日志文件路径
otel:
  endpoint: 127.0.0.1:4317
  service-name: art-apiserver
  output-mode: otel
  level: debug
  add-source: true
  use-prometheus-endpoint: true
  slog: # 改配置项只有 output-mod 为 slog 时生效
    format: text
    time-format: "2006-01-02 15:04:05"
    output: stdout
redis:
  addr: 127.0.0.1:6379 # Redis 地址
  database: 0 # Redis 数据库索引
  password: 123456 # Redis 密码
mysql:  
  addr: 127.0.0.1:3306
  username: art
  password: "123456"
  database: art
  max-connection-life-time: 10s
  max-idle-connections: 100
  max-open-connections: 100

